### ISSUE TITLE
Staging Environment Missing Template lockup/lockup/unlock

### ISSUE THREAD

**Issue by bvlaar** [gblakeman/lockup#22]
I have integrated lockup into an existing rails 4.1.0 Rails application. I set an environment variable in my staging environment (Heroku) for lockup and I've mounted lockup at the top of my routes.rb file. When I visit my staging environment, I hit the lockup screen and it works perfectly. I'm struggling to recreate this error on my own.

My bug tracker is reporting the following error:

`ActionView::MissingTemplate: Missing template lockup/lockup/unlock, lockup/application/unlock with {:locale=>[:en], :formats=>["image/*"], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :jbuilder, :coffee]}. Searched in: * "/app/app/views" * "/app/vendor/bundle/ruby/1.9.1/gems/lockup-1.3.1/app/views" * `

Can anyone shed some light on how I can debug this issue further?
Thank you!

**Comment by gblakeman** [comment]
@bvlaar Hi Brandon, would you upgrade to the latest version of the gem (1.3.1.2) and see if you still get the issue with Heroku?

**Comment by bvlaar** [comment]
@gblakeman Looks like that solved the issue. Thank you for the heads up.

**Comment by gblakeman** [comment]
@bvlaar Awesome, glad that worked! And thanks for the kind words; it's great to see the gem used!
