### ISSUE TITLE
changing the text and styling.

### ISSUE THREAD

**Issue by othaimeen** [gblakeman/lockup#23]
hello,

i just have one question: is there a way i can change the text and styling of the unlocking page? 

thank you.

**Comment by gblakeman** [comment]
@othaimeen Not currently (other than forking it). I wanted it to render as a single template without any css/js or configuration dependencies, so everything is contained in `app/views/layouts/lockup/`.

You could fork it and modify those files if you wanted to customize it.

**Comment by danrabinowitz** [comment]
I don't think that's correct. I've submitted a PR describing how to do what @othaimeen is asking.

https://github.com/gblakeman/lockup/pull/25

@othaimeen, does this PR help?

**Comment by gblakeman** [comment]
Ahh, super-good point @danrabinowitz! I was only thinking of it within the idea of providing customization functionality (something I had considered at one point). This is a great way to provide custom overrides of the existing style/design. /cc @othaimeen

I'll get that pull in when I’ve got a moment.

**Comment by othaimeen** [comment]
@danrabinowitz  awesome! I just tried it out, and it's working great. thank you so much.
