### ISSUE TITLE
Rails 5 support

### ISSUE THREAD

**Issue by arael** [gblakeman/lockup#27]
Could you please make this gem compatible with rails 5? When I try to install it I get:

``
conflicting dependencies rails (< 5, >= 3) and rails (~> 5.0.0, ~> 5.0.0) (Gem::DependencyResolutionError)
  Activated rails-5.0.0
  which does not match conflicting dependency (< 5, >= 3)
``

**Comment by danrabinowitz** [comment]
I thought that would be a simple update, but it wasn't!

That said, I was able to loosen the constraints on the Rails version to allow version 5. I've submitted a PR here: https://github.com/gblakeman/lockup/pull/30

**Comment by arael** [comment]
Thank you

**Comment by gblakeman** [comment]
@arael Version 1.4 is now pushed to RubyGems, so you should be able to install it normally now and have Rails 5 support!

**Comment by arael** [comment]
@gblakeman Thank you very much!!
