### ISSUE TITLE
Doesn't work well with the health_check gem

### ISSUE THREAD

**Issue by ndbroadbent** [gblakeman/lockup#32]
First of all, thanks for the awesome gem! This is really useful, and very easy to set up.

I'm trying to get it to work with the [health_check](https://github.com/ianheggie/health_check) gem. I'm seeing the following error from `HealthCheck::HealthCheckController`:

```
In order to use #url_for, you must include routing helpers explicitly. For instance, `include Rails.application.routes.url_helpers`.
```

This might be because I'm setting default `url_options` in my enviroment, like this:

```ruby
  Rails.application.routes.default_url_options =
  config.action_controller.default_url_options = {
    host: ENV['APP_DOMAIN_NAME'],
    protocol: 'https'
  }
``` 

I'm not sure about the best way to handle this. There's a few options:

* Turn off the health_check basic authentication for staging, and just redirect to the lockup page if the `lockup_codeword` param is incorrect.
* Make `lockup` ignore the `/health/all` route, and keep using basic authentication.
* Use both basic authentication PLUS the `lockup_codeword` param. I don't think that's necessary, but it would be good to support this case anyway.

**Comment by ndbroadbent** [comment]
I figured out a quick workaround. In `config/routes.rb`:

```
Rails.application.routes.draw do
  if ENV['STAGING']
    # Password-protect the staging environment
    # Password is set in ENV['LOCKUP_CODEWORD']
    mount Lockup::Engine, at: '/lockup'

    # Remove lockup from health_check (uses basic auth)
    class ::HealthCheck::HealthCheckController
      skip_before_action :check_for_lockup
    end
  end

```

**Comment by ndbroadbent** [comment]
OK I finally figured out something that works. I configure the `health_check` gem in `config/initializers/health_check.rb`, so I added this to the bottom:

```ruby
# Disable lockup in health_check controller (uses basic auth)
class HealthCheck::HealthCheckController
  def lockup_codeword_present?
    false
  end
end
```

This fixes the crash for my health check, but I'm still getting crashes for other engines, such as [rswag](https://github.com/domaindrivendev/rswag) for API documentation.

**Comment by danrabinowitz** [comment]
You could also add `skip_before_action :check_for_lockup` to the `HealthCheck::HealthCheckController` as described here:
https://github.com/gblakeman/lockup#use-lockup-around-a-specific-controller

**Comment by danrabinowitz** [comment]
It looks like you can close this issue, since you found a solution.

**Comment by ndbroadbent** [comment]
Ah yes, I did try adding the `skip_before_action`, but that crashed my server when I deployed to staging. Something to do with the order of loading classes, so I got an error saying that the "check_for_lockup" action had not been registered.

OK yep will close this for now, I think the workaround is ok
