### ISSUE TITLE
Crashes in other engines if I don't mount the lockup engine on production

### ISSUE THREAD

**Issue by ndbroadbent** [gblakeman/lockup#33]
I wanted to make sure that I wasn't using this on production, so I wrote the following code:

```ruby
Rails.application.routes.draw do
  if ENV['STAGING']
    mount Lockup::Engine, at: '/lockup'
  end
```

However, I'm using a library called [rswag](https://github.com/domaindrivendev/rswag) for API documentation, which also mounts an engine in my routes. When I call that route, I get:

```
NameError - undefined local variable or method `lockup' for #<Rswag::Ui::HomeController:0x00007fa5ae4d6998>:
  lockup (1.4) lib/lockup.rb:25:in `check_for_lockup'
```

I've fixed this in my fork by checking that `lockup` is defined: https://github.com/ndbroadbent/lockup/commit/3079e44f12fd717a727c3dace16f3a7651891d5b

(Also some refactoring.)

**Comment by danrabinowitz** [comment]
You can safely use it in production, and as long as `LOCKUP_CODEWORD` isn't set then it won't do anything. The performance penalty is negligible.

That said, the commit on your fork seems reasonable. Maybe submit it as a PR?
