### ISSUE TITLE
Cookie lifetime

### ISSUE THREAD

**Issue by MariusDanner** [gblakeman/lockup#36]
Is there a way to change the lifetime of the cookie in my application?

**Comment by danrabinowitz** [comment]
I’m curious: What’s the use case for that?

**Comment by MariusDanner** [comment]
We have a university project that we need to share with our project partner and they felt that a cookie lifespan of 5years is unsecure. So they wanted to be prompted for their password more often ^^
I forked the repo and made the lifetime customisable via an environment variable or the secrets.yaml

**Comment by gblakeman** [comment]
Ah, interesting scenario @MariusDanner.

My original vision for **Lockup** never meant for it to be _actual_ security, but more of a stop-gap against casual bad actors, mistaken access, or search engines for in-development projects.

Couple that vision with the fact that simply changing the passcode will prompt someone to re-authenticate (with the new code, of course) and I’m not sure it makes much sense to add another feature/preference to the gem. I like the existing simplicity.

What do you think @danrabinowitz?

**Comment by danrabinowitz** [comment]
I don't see any reason not to allow custom behavior, since it's so simple: https://github.com/gblakeman/lockup/pull/37

**Comment by danrabinowitz** [comment]
Handled by https://github.com/gblakeman/lockup/pull/37
