### ISSUE TITLE
Locking a website/API

### ISSUE THREAD

**Issue by jfanals** [gblakeman/lockup#38]
I am currently using lockup to lock a website that is also accessed as API. I have tried using the "?lockup_codeword=love" in the the API call URL but is looks like it is not working as the json payload gets lost on the redirect.

Is there a way to whitelist a server/ip address so that there is no need to use the lockup_codeword redirect?

Thanks

**Comment by gblakeman** [comment]
Yeah, nothing about Lockup is currently designed to work with an API or JSON payload.

You can always set up some before filters that [skip Lockup](https://github.com/gblakeman/lockup/blob/master/README.md#advanced-usage).

**Comment by jfanals** [comment]
Thank you @gblakeman for your quick response.

I am trying the skipping method, using this line in the `application_controller.rb` file:

    skip_before_action :check_for_lockup

But the lockup gem is still being triggered, even without adding the `before_action :check_for_lockup` in any controller.

What am I missing?

**Comment by danrabinowitz** [comment]
Maybe try skip_before_filter instead of skip_before_action? Which one to use depends on your version of Rails.

**Comment by jfanals** [comment]
I have tried with `skip_before_filter` and `skip_before_action`, and neither of them skip the `check_for_lockup` method.
(using Rails 4.1.2)

**Comment by gblakeman** [comment]
@jfanals So you can confirm that neither `skip_before_action :check_for_lockup` nor `skip_before_filter :check_for_lockup` at the top of `application_controller.rb` is working for you on Rails 4.1.X?

**Comment by jfanals** [comment]
@gblakeman I confirm that neither of the `skip_before_action :check_for_lockup` nor the `skip_before_filter :check_for_lockup` work **right after the server has been restarted**.

But they do work if I make a change to the `application_controller.rb` and the ApplicationController code gets re executed.

It looks like a bug.

**Comment by jfanals** [comment]
Yes, it also does not work in `staging` (where the lockup gem is used).

**Comment by gblakeman** [comment]
I created a separate issue for this. Let’s continue any conversation in #39.
