### ISSUE TITLE
Investigate skip_before_x actions

### ISSUE THREAD

**Issue by gblakeman** [gblakeman/lockup#39]
Followup on an issue [that surfaced](
https://github.com/gblakeman/lockup/issues/38#issuecomment-407499995) in #38.

> @gblakeman I confirm that neither of the skip_before_action :check_for_lockup nor the skip_before_filter :check_for_lockup work right after the server has been restarted.

> But they do work if I make a change to the application_controller.rb and the ApplicationController code gets re executed. (in development mode)

> It looks like a bug.

**Comment by guaguasi** [comment]
@gblakeman Is this still an issue? Does this only affect 4.1.X?

**Comment by gblakeman** [comment]
@guaguasi I was never able to reproduce it and was leaving it open to investigate further, but haven’t had the time. Have you run into a similar issue?

**Comment by gblakeman** [comment]
I have not been able to re-produce either. Closing it for now.
